---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "alphafold-gradio.fullname" . }}-data
spec:
  accessModes:
    - {{ .Values.dataPersistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.dataPersistence.size | quote }}
  {{- if .Values.dataPersistence.storageClass }}
  {{- if (eq "-" .Values.dataPersistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.dataPersistence.storageClass }}"
  {{- end }}
  {{- end }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "alphafold-gradio.fullname" . }}-output
spec:
  accessModes:
    - {{ .Values.outputPersistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.outputPersistence.size | quote }}
  {{- if .Values.outputPersistence.storageClass }}
  {{- if (eq "-" .Values.outputPersistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.outputPersistence.storageClass }}"
  {{- end }}
  {{- end }}
